//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLServerManagerModern.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLServerManagerModern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional paramaters.
        /// </summary>
        public static string AdditionalParameters {
            get {
                return ResourceManager.GetString("AdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other category.
        /// </summary>
        public static string AddOtherCategory {
            get {
                return ResourceManager.GetString("AddOtherCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other protocol.
        /// </summary>
        public static string AddOtherProtocol {
            get {
                return ResourceManager.GetString("AddOtherProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address field cannot be empty..
        /// </summary>
        public static string AddressCannotBeEmpty {
            get {
                return ResourceManager.GetString("AddressCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address unreachable.
        /// </summary>
        public static string AddressUnreachable {
            get {
                return ResourceManager.GetString("AddressUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow diagnostics of port availability.
        /// </summary>
        public static string AllowPortAvailabilityDiagnostics {
            get {
                return ResourceManager.GetString("AllowPortAvailabilityDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet associated this protocol to program, would you like to do it now?.
        /// </summary>
        public static string AssociateMessage {
            get {
                return ResourceManager.GetString("AssociateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While adding an association, write the startup argument into input field and replace the ip and port variable with {ip} and {port}. This is commonly in this form: &quot;&lt;command/protocol&gt; &lt;remote IP endpoint&gt;:&lt;port&gt;&quot;. An example for a program Putty: -ssh {ip}:{port}.
        /// </summary>
        public static string AssociationsTip {
            get {
                return ResourceManager.GetString("AssociationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        public static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Associations.
        /// </summary>
        public static string CategoryAssociations {
            get {
                return ResourceManager.GetString("CategoryAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category and color association.
        /// </summary>
        public static string CategoryColorAssociation {
            get {
                return ResourceManager.GetString("CategoryColorAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default category color is already defined..
        /// </summary>
        public static string CategoryColorDefined {
            get {
                return ResourceManager.GetString("CategoryColorDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string ClusterWindow {
            get {
                return ResourceManager.GetString("ClusterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmd parameters.
        /// </summary>
        public static string CmdParameters {
            get {
                return ResourceManager.GetString("CmdParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from CSV file.
        /// </summary>
        public static string CSVImportDialog {
            get {
                return ResourceManager.GetString("CSVImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a valid import from csv files thre are 4 files required, after an export from this application these files are called: *-servers.csv; *-addresses.csv; *-serverContents.csv and *-defaultCategories. If the import is to be proceed with without any issues, all required files need to be specified.
        ///Fileds marked with * have to be filled in otherwise the import cannot proceed..
        /// </summary>
        public static string CSVImportDialogMessage {
            get {
                return ResourceManager.GetString("CSVImportDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV structure file.
        /// </summary>
        public static string CSVStructureFile {
            get {
                return ResourceManager.GetString("CSVStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current color.
        /// </summary>
        public static string CurrentColor {
            get {
                return ResourceManager.GetString("CurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default protocol is already present. To proceed with this action edit the association or delete it. (Ports added by the application cannot be changed)..
        /// </summary>
        public static string DefaultProtocolAlreadyPresent {
            get {
                return ResourceManager.GetString("DefaultProtocolAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Entry not found.
        /// </summary>
        public static string DNSEntryNotFound {
            get {
                return ResourceManager.GetString("DNSEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate entries have been found inside the list, please check for duplicates and remove all the invalid ones. (Only the first entry of one protocol will be saved).
        /// </summary>
        public static string DuplicateProtocolEntries {
            get {
                return ResourceManager.GetString("DuplicateProtocolEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit server.
        /// </summary>
        public static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access this directory, you need to launch this application as an administrator. Do you want to elevate this process?.
        /// </summary>
        public static string ElevateProcess {
            get {
                return ResourceManager.GetString("ElevateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate process.
        /// </summary>
        public static string ElevateProcessCaption {
            get {
                return ResourceManager.GetString("ElevateProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to executable file.
        /// </summary>
        public static string ExecutableFilePath {
            get {
                return ResourceManager.GetString("ExecutableFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file does not exist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindHeader {
            get {
                return ResourceManager.GetString("FindHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size is not specified (the default or saved value is used)..
        /// </summary>
        public static string FontSizeNull {
            get {
                return ResourceManager.GetString("FontSizeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified font size is too large (the largest value is used)..
        /// </summary>
        public static string FontSizeTooLarge {
            get {
                return ResourceManager.GetString("FontSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified font size is too small (the lowest value is used)..
        /// </summary>
        public static string FontSizeTooSmall {
            get {
                return ResourceManager.GetString("FontSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FQDN.
        /// </summary>
        public static string FQDN {
            get {
                return ResourceManager.GetString("FQDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML notation.
        /// </summary>
        public static string HTMLNotation {
            get {
                return ResourceManager.GetString("HTMLNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is virtual.
        /// </summary>
        public static string IsVirtual {
            get {
                return ResourceManager.GetString("IsVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON structure file.
        /// </summary>
        public static string JSONStructureFile {
            get {
                return ResourceManager.GetString("JSONStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to local file.
        /// </summary>
        public static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match exactly.
        /// </summary>
        public static string MatchExactly {
            get {
                return ResourceManager.GetString("MatchExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in miliseconds (ms).
        /// </summary>
        public static string Miliseconds {
            get {
                return ResourceManager.GetString("Miliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cluster.
        /// </summary>
        public static string NewCluster {
            get {
                return ResourceManager.GetString("NewCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server.
        /// </summary>
        public static string NewServer {
            get {
                return ResourceManager.GetString("NewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New server structure.
        /// </summary>
        public static string NewServerStructure {
            get {
                return ResourceManager.GetString("NewServerStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New virtualization server.
        /// </summary>
        public static string NewVirtualizationServer {
            get {
                return ResourceManager.GetString("NewVirtualizationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address is not a valid source address..
        /// </summary>
        public static string NotValidDestinationAddress {
            get {
                return ResourceManager.GetString("NotValidDestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file with servers structure.
        /// </summary>
        public static string OFDSelectFile {
            get {
                return ResourceManager.GetString("OFDSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local structure.
        /// </summary>
        public static string OpenLocal {
            get {
                return ResourceManager.GetString("OpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open remote structure.
        /// </summary>
        public static string OpenRemote {
            get {
                return ResourceManager.GetString("OpenRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open watcher.
        /// </summary>
        public static string OpenWatcher {
            get {
                return ResourceManager.GetString("OpenWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other....
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the category.
        /// </summary>
        public static string OtherCategoryName {
            get {
                return ResourceManager.GetString("OtherCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the protocol.
        /// </summary>
        public static string OtherProtocolName {
            get {
                return ResourceManager.GetString("OtherProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol to Port Association.
        /// </summary>
        public static string PortAssociation {
            get {
                return ResourceManager.GetString("PortAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port asscociations.
        /// </summary>
        public static string PortAssociations {
            get {
                return ResourceManager.GetString("PortAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port not responding.
        /// </summary>
        public static string PortNotResponding {
            get {
                return ResourceManager.GetString("PortNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected protocol has no associated port with it, therefor it is necessary to enter port number (port cannot be empty)..
        /// </summary>
        public static string PortUnassociatedAndEmpty {
            get {
                return ResourceManager.GetString("PortUnassociatedAndEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Association.
        /// </summary>
        public static string ProgramAssociation {
            get {
                return ResourceManager.GetString("ProgramAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Selection.
        /// </summary>
        public static string ProgramSelection {
            get {
                return ResourceManager.GetString("ProgramSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program&apos;s Start Arguments.
        /// </summary>
        public static string ProtocolAssociation {
            get {
                return ResourceManager.GetString("ProtocolAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol associations.
        /// </summary>
        public static string ProtocolAssociations {
            get {
                return ResourceManager.GetString("ProtocolAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol cannot be empty..
        /// </summary>
        public static string ProtocolCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProtocolCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        public static string Protocols {
            get {
                return ResourceManager.GetString("Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to remote file.
        /// </summary>
        public static string RemoteFile {
            get {
                return ResourceManager.GetString("RemoteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete server.
        /// </summary>
        public static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the server?.
        /// </summary>
        public static string RemoveServerMessage {
            get {
                return ResourceManager.GetString("RemoveServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew time.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew value is not specified (the default or saved value is used)..
        /// </summary>
        public static string RenewNull {
            get {
                return ResourceManager.GetString("RenewNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified renew is too small (the lowest value is used)..
        /// </summary>
        public static string RenewTooSmall {
            get {
                return ResourceManager.GetString("RenewTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerWindow {
            get {
                return ResourceManager.GetString("ServerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a destination and a file name.
        /// </summary>
        public static string SFDFileSavingProcedure {
            get {
                return ResourceManager.GetString("SFDFileSavingProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show modification indicators.
        /// </summary>
        public static string ShowLocalModifiers {
            get {
                return ResourceManager.GetString("ShowLocalModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows local modification indicators (available only with remote server file set)..
        /// </summary>
        public static string ShowLocalModifiersToolTip {
            get {
                return ResourceManager.GetString("ShowLocalModifiersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite database file.
        /// </summary>
        public static string SQLiteDBFile {
            get {
                return ResourceManager.GetString("SQLiteDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize local with remote.
        /// </summary>
        public static string SyncRemote {
            get {
                return ResourceManager.GetString("SyncRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TForTest {
            get {
                return ResourceManager.GetString("TForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout value is not specified (the default or saved value is used)..
        /// </summary>
        public static string TimeoutNull {
            get {
                return ResourceManager.GetString("TimeoutNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified timeout value is too small (the lowest value is used)..
        /// </summary>
        public static string TimeoutTooSmall {
            get {
                return ResourceManager.GetString("TimeoutTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve or parse the specified address. Please, check if the address has been entered correctly. (The address will be saved, but the connection might fail).
        /// </summary>
        public static string UnableToResolveOrParse {
            get {
                return ResourceManager.GetString("UnableToResolveOrParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untested.
        /// </summary>
        public static string Untested {
            get {
                return ResourceManager.GetString("Untested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtualization Server.
        /// </summary>
        public static string VirtualizationServerWindow {
            get {
                return ResourceManager.GetString("VirtualizationServerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under current settings (this server being a virtualization server) all servers in collection currently listed as physical machines need to be virtual. This will be handled automatically. Do you wish to proceed with this action?.
        /// </summary>
        public static string VirtualServerSwitch {
            get {
                return ResourceManager.GetString("VirtualServerSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual server switch.
        /// </summary>
        public static string VirtualServerSwitchCaption {
            get {
                return ResourceManager.GetString("VirtualServerSwitchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher.
        /// </summary>
        public static string WatcherWindow {
            get {
                return ResourceManager.GetString("WatcherWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML structure file.
        /// </summary>
        public static string XMLStructureFile {
            get {
                return ResourceManager.GetString("XMLStructureFile", resourceCulture);
            }
        }
    }
}
