//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLServerManagerModern.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLServerManagerModern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Additional paramaters.
        /// </summary>
        public static string AdditionalParameters {
            get {
                return ResourceManager.GetString("AdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add other category.
        /// </summary>
        public static string AddOtherCategory {
            get {
                return ResourceManager.GetString("AddOtherCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add other protocol.
        /// </summary>
        public static string AddOtherProtocol {
            get {
                return ResourceManager.GetString("AddOtherProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Address field cannot be empty..
        /// </summary>
        public static string AddressCannotBeEmpty {
            get {
                return ResourceManager.GetString("AddressCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Address unreachable.
        /// </summary>
        public static string AddressUnreachable {
            get {
                return ResourceManager.GetString("AddressUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Allow diagnostics of port availability.
        /// </summary>
        public static string AllowPortAvailabilityDiagnostics {
            get {
                return ResourceManager.GetString("AllowPortAvailabilityDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You have not yet associated this protocol to program, would you like to do it now?.
        /// </summary>
        public static string AssociateMessage {
            get {
                return ResourceManager.GetString("AssociateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný While adding an association, write the startup argument into the input field and replace the ip and port variable with {address} and {port}. This is usually follows this format: &quot;&lt;command/protocol&gt; &lt;remote IP endpoint&gt;:&lt;port&gt;&quot;. An example for a program Putty: -ssh {address} -P {port}.
        /// </summary>
        public static string AssociationsTip {
            get {
                return ResourceManager.GetString("AssociationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Border color.
        /// </summary>
        public static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Category Associations.
        /// </summary>
        public static string CategoryAssociations {
            get {
                return ResourceManager.GetString("CategoryAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Category and color association.
        /// </summary>
        public static string CategoryColorAssociation {
            get {
                return ResourceManager.GetString("CategoryColorAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Default category color is already defined..
        /// </summary>
        public static string CategoryColorDefined {
            get {
                return ResourceManager.GetString("CategoryColorDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cluster.
        /// </summary>
        public static string ClusterWindow {
            get {
                return ResourceManager.GetString("ClusterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cmd parameters.
        /// </summary>
        public static string CmdParameters {
            get {
                return ResourceManager.GetString("CmdParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Import from CSV file.
        /// </summary>
        public static string CSVImportDialog {
            get {
                return ResourceManager.GetString("CSVImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný For a valid import from csv files there are 4 files required, after an export from this application these files are called: *-servers.csv; *-addresses.csv; *-serverContents.csv and *-defaultCategories. In order to proceed with import without any issues, all required files need to be specified.
        ///Fields marked with * have to be filled in, otherwise the import cannot continue..
        /// </summary>
        public static string CSVImportDialogMessage {
            get {
                return ResourceManager.GetString("CSVImportDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CSV structure file.
        /// </summary>
        public static string CSVStructureFile {
            get {
                return ResourceManager.GetString("CSVStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Current color.
        /// </summary>
        public static string CurrentColor {
            get {
                return ResourceManager.GetString("CurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Database name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Default protocol is already present. To proceed with this action edit the association or delete it. (Ports added by the application cannot be changed)..
        /// </summary>
        public static string DefaultProtocolAlreadyPresent {
            get {
                return ResourceManager.GetString("DefaultProtocolAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný DNS Entry not found.
        /// </summary>
        public static string DNSEntryNotFound {
            get {
                return ResourceManager.GetString("DNSEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Download only remote default colors..
        /// </summary>
        public static string DownloadDefaultColorsOnly {
            get {
                return ResourceManager.GetString("DownloadDefaultColorsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Download only remote structures..
        /// </summary>
        public static string DownloadEntitiesOnly {
            get {
                return ResourceManager.GetString("DownloadEntitiesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Do not send data, but fully synchronize..
        /// </summary>
        public static string DownloadToFullSync {
            get {
                return ResourceManager.GetString("DownloadToFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duplicate entries have been found inside the list, please check for duplicates and remove all the invalid ones. (Only the first entry of one protocol will be saved).
        /// </summary>
        public static string DuplicateProtocolEntries {
            get {
                return ResourceManager.GetString("DuplicateProtocolEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Edit server.
        /// </summary>
        public static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný To access this directory, you need to launch this application as an administrator. Do you want to elevate this process?.
        /// </summary>
        public static string ElevateProcess {
            get {
                return ResourceManager.GetString("ElevateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elevate process.
        /// </summary>
        public static string ElevateProcessCaption {
            get {
                return ResourceManager.GetString("ElevateProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chyba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path to executable file.
        /// </summary>
        public static string ExecutableFilePath {
            get {
                return ResourceManager.GetString("ExecutableFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Executable files.
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This file does not exist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Find.
        /// </summary>
        public static string FindHeader {
            get {
                return ResourceManager.GetString("FindHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Font size is not specified (the default or saved value is used)..
        /// </summary>
        public static string FontSizeNull {
            get {
                return ResourceManager.GetString("FontSizeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specified font size is too large (the largest value is used)..
        /// </summary>
        public static string FontSizeTooLarge {
            get {
                return ResourceManager.GetString("FontSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specified font size is too small (the lowest value is used)..
        /// </summary>
        public static string FontSizeTooSmall {
            get {
                return ResourceManager.GetString("FontSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FQDN.
        /// </summary>
        public static string FQDN {
            get {
                return ResourceManager.GetString("FQDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hide virtual machines.
        /// </summary>
        public static string HideVirtuals {
            get {
                return ResourceManager.GetString("HideVirtuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hostname.
        /// </summary>
        public static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný HTML notation.
        /// </summary>
        public static string HTMLNotation {
            get {
                return ResourceManager.GetString("HTMLNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Is virtual.
        /// </summary>
        public static string IsVirtual {
            get {
                return ResourceManager.GetString("IsVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný JSON structure file.
        /// </summary>
        public static string JSONStructureFile {
            get {
                return ResourceManager.GetString("JSONStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep.
        /// </summary>
        public static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path to local file.
        /// </summary>
        public static string LocalLocation {
            get {
                return ResourceManager.GetString("LocalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Match exactly.
        /// </summary>
        public static string MatchExactly {
            get {
                return ResourceManager.GetString("MatchExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time in miliseconds (ms).
        /// </summary>
        public static string Miliseconds {
            get {
                return ResourceManager.GetString("Miliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ms.
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný MySQL Credentials.
        /// </summary>
        public static string MySQLLoginData {
            get {
                return ResourceManager.GetString("MySQLLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New cluster.
        /// </summary>
        public static string NewCluster {
            get {
                return ResourceManager.GetString("NewCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New server.
        /// </summary>
        public static string NewServer {
            get {
                return ResourceManager.GetString("NewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New server structure.
        /// </summary>
        public static string NewServerStructure {
            get {
                return ResourceManager.GetString("NewServerStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New virtualization server.
        /// </summary>
        public static string NewVirtualizationServer {
            get {
                return ResourceManager.GetString("NewVirtualizationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This address is not a valid source address..
        /// </summary>
        public static string NotValidDestinationAddress {
            get {
                return ResourceManager.GetString("NotValidDestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose a file with servers structure.
        /// </summary>
        public static string OFDSelectFile {
            get {
                return ResourceManager.GetString("OFDSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open local structure.
        /// </summary>
        public static string OpenLocal {
            get {
                return ResourceManager.GetString("OpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open remote structure.
        /// </summary>
        public static string OpenRemote {
            get {
                return ResourceManager.GetString("OpenRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open Watcher.
        /// </summary>
        public static string OpenWatcher {
            get {
                return ResourceManager.GetString("OpenWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný other....
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name of the category.
        /// </summary>
        public static string OtherCategoryName {
            get {
                return ResourceManager.GetString("OtherCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name of the protocol.
        /// </summary>
        public static string OtherProtocolName {
            get {
                return ResourceManager.GetString("OtherProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Protocol to Port Association.
        /// </summary>
        public static string PortAssociation {
            get {
                return ResourceManager.GetString("PortAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port asscociations.
        /// </summary>
        public static string PortAssociations {
            get {
                return ResourceManager.GetString("PortAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port not responding.
        /// </summary>
        public static string PortNotResponding {
            get {
                return ResourceManager.GetString("PortNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected protocol has no associated port with it, therefor it is necessary to enter port number (port cannot be empty)..
        /// </summary>
        public static string PortUnassociatedAndEmpty {
            get {
                return ResourceManager.GetString("PortUnassociatedAndEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Program Association.
        /// </summary>
        public static string ProgramAssociation {
            get {
                return ResourceManager.GetString("ProgramAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Program Selection.
        /// </summary>
        public static string ProgramSelection {
            get {
                return ResourceManager.GetString("ProgramSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Program&apos;s Start Arguments.
        /// </summary>
        public static string ProtocolAssociation {
            get {
                return ResourceManager.GetString("ProtocolAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Protocol associations.
        /// </summary>
        public static string ProtocolAssociations {
            get {
                return ResourceManager.GetString("ProtocolAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Protocol cannot be empty..
        /// </summary>
        public static string ProtocolCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProtocolCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Protocols.
        /// </summary>
        public static string Protocols {
            get {
                return ResourceManager.GetString("Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Path to remote file.
        /// </summary>
        public static string RemoteLocation {
            get {
                return ResourceManager.GetString("RemoteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Remote MySQL database specification.
        /// </summary>
        public static string RemoteMySQLDatabase {
            get {
                return ResourceManager.GetString("RemoteMySQLDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete server.
        /// </summary>
        public static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Are you sure you want to remove the server?.
        /// </summary>
        public static string RemoveServerMessage {
            get {
                return ResourceManager.GetString("RemoveServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Renew time.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Renew value is not specified (the default or saved value is used)..
        /// </summary>
        public static string RenewNull {
            get {
                return ResourceManager.GetString("RenewNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specified renew is too small (the lowest value is used)..
        /// </summary>
        public static string RenewTooSmall {
            get {
                return ResourceManager.GetString("RenewTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Resolve.
        /// </summary>
        public static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Search for.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Send data and fully synchronize..
        /// </summary>
        public static string SendDataAndFullySynchronize {
            get {
                return ResourceManager.GetString("SendDataAndFullySynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Send only default colors..
        /// </summary>
        public static string SendDefaultColorsOnly {
            get {
                return ResourceManager.GetString("SendDefaultColorsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Server.
        /// </summary>
        public static string ServerWindow {
            get {
                return ResourceManager.GetString("ServerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose a destination and a file name.
        /// </summary>
        public static string SFDFileSavingProcedure {
            get {
                return ResourceManager.GetString("SFDFileSavingProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show details view.
        /// </summary>
        public static string ShowDetailsView {
            get {
                return ResourceManager.GetString("ShowDetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show modification indicators.
        /// </summary>
        public static string ShowLocalModifiers {
            get {
                return ResourceManager.GetString("ShowLocalModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shows local modification indicators (available only with remote server file set)..
        /// </summary>
        public static string ShowLocalModifiersToolTip {
            get {
                return ResourceManager.GetString("ShowLocalModifiersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SQLite database file.
        /// </summary>
        public static string SQLiteDBFile {
            get {
                return ResourceManager.GetString("SQLiteDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization - conflicts.
        /// </summary>
        public static string SynchronizationConflictResolutionWindowTitle {
            get {
                return ResourceManager.GetString("SynchronizationConflictResolutionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization - connection.
        /// </summary>
        public static string SynchronizationConnectionWindowTitle {
            get {
                return ResourceManager.GetString("SynchronizationConnectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization failed, error:.
        /// </summary>
        public static string SynchronizationFailed {
            get {
                return ResourceManager.GetString("SynchronizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization Failure.
        /// </summary>
        public static string SynchronizationFailure {
            get {
                return ResourceManager.GetString("SynchronizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization - login.
        /// </summary>
        public static string SynchronizationLoginPopupTitle {
            get {
                return ResourceManager.GetString("SynchronizationLoginPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization Success.
        /// </summary>
        public static string SynchronizationSuccess {
            get {
                return ResourceManager.GetString("SynchronizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronization was sucessful..
        /// </summary>
        public static string SynchronizationSuccessful {
            get {
                return ResourceManager.GetString("SynchronizationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronize.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronize local with remote.
        /// </summary>
        public static string SyncRemote {
            get {
                return ResourceManager.GetString("SyncRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TCP.
        /// </summary>
        public static string TCP {
            get {
                return ResourceManager.GetString("TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný T.
        /// </summary>
        public static string TForTest {
            get {
                return ResourceManager.GetString("TForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Replace.
        /// </summary>
        public static string ThrowAway {
            get {
                return ResourceManager.GetString("ThrowAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Timeout value is not specified (the default or saved value is used)..
        /// </summary>
        public static string TimeoutNull {
            get {
                return ResourceManager.GetString("TimeoutNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Specified timeout value is too small (the lowest value is used)..
        /// </summary>
        public static string TimeoutTooSmall {
            get {
                return ResourceManager.GetString("TimeoutTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UDP.
        /// </summary>
        public static string UDP {
            get {
                return ResourceManager.GetString("UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unable to resolve or parse the specified address. Please, check if the address has been entered correctly. (The address will be saved, but the connection might fail).
        /// </summary>
        public static string UnableToResolveOrParse {
            get {
                return ResourceManager.GetString("UnableToResolveOrParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Untested.
        /// </summary>
        public static string Untested {
            get {
                return ResourceManager.GetString("Untested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Virtualization Server.
        /// </summary>
        public static string VirtualizationServerWindow {
            get {
                return ResourceManager.GetString("VirtualizationServerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Under current settings (this server being a virtualization server) all servers in collection currently listed as physical machines need to be virtual. This will be handled automatically. Do you wish to proceed with this action?.
        /// </summary>
        public static string VirtualServerSwitch {
            get {
                return ResourceManager.GetString("VirtualServerSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Virtual server switch.
        /// </summary>
        public static string VirtualServerSwitchCaption {
            get {
                return ResourceManager.GetString("VirtualServerSwitchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Watcher.
        /// </summary>
        public static string WatcherWindow {
            get {
                return ResourceManager.GetString("WatcherWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XML structure file.
        /// </summary>
        public static string XMLStructureFile {
            get {
                return ResourceManager.GetString("XMLStructureFile", resourceCulture);
            }
        }
    }
}
